version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: server
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      mongo_db:
        condition: service_started
    command: npm start

  mongo_db:
    image: mongo:5.0.8
    container_name: mongo_db
    ports:
      - 27017:27017
    command: mongod --quiet --logpath /dev/null
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/healthcheck-database --quiet

volumes:
  node_modules:
