name: Books Server

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        run: docker build -t akshaysdev/books .
      - name: Publish image to Docker Hub
        run: docker push akshaysdev/books:latest
      - name: Deploying the pushed image to Render
        run: curl ${{ secrets.RENDER_HOOK }}